language: node_js
node_js:
  - "node"
cache:
  directories:
    - "blazingly-fast-blog/node_modules" # This will tell Travis CI to cache the dependencies

before_install:
  - pwd
  - ls
  - cd blazingly-fast-blog

install:
  - yarn # install dependencies

before_script:
  - yarn build # build project
  - yarn test:size # run performance prechecks

script:
  - NOW_URL="$(now --public --token=$NOW_TOKEN --team=inovex)" # deploy to now
  # store deployment url from clipboard into the deployment url
  - echo $NOW_URL

after_success:
  # https://graysonkoonce.com/getting-the-current-branch-name-during-a-pull-request-in-travis-ci/
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  # alias url only when deploying master branch
  - ls
  - if [ $BRANCH = master ]; then now alias --token=$NOW_TOKEN; fi
  # - $BRANCH=master && npm run alias
  - npm run lh $NOW_URL
  - TEST_URL=$NOW_URL GIT_TOKEN=$GIT_TOKEN WEBPAGETEST_API_KEY=$WEBPAGETEST_API_KEY GIT_BRANCH=$TRAVIS_BRANCH node webPageTest.js
